// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShortenURL.Data.Context;

#nullable disable

namespace ShortenURL.Data.Migrations
{
    [DbContext(typeof(ShortenUrlDbContext))]
    partial class ShortenUrlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShortenURL.Data.Models.NewUrl", b =>
                {
                    b.Property<int>("NewLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NewLink")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("OriginalLinkId")
                        .HasColumnType("int");

                    b.HasKey("NewLinkId");

                    b.HasIndex("OriginalLinkId");

                    b.ToTable("NewUrl");
                });

            modelBuilder.Entity("ShortenURL.Data.Models.OriginalUrl", b =>
                {
                    b.Property<int>("OriginalLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("OriginalLink")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("OriginalLinkId");

                    b.HasIndex("OriginalLink")
                        .IsUnique();

                    b.ToTable("OriginalUrl");
                });

            modelBuilder.Entity("ShortenURL.Data.Models.NewUrl", b =>
                {
                    b.HasOne("ShortenURL.Data.Models.OriginalUrl", "OriginalUrl")
                        .WithMany()
                        .HasForeignKey("OriginalLinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginalUrl");
                });
#pragma warning restore 612, 618
        }
    }
}
